on:
  workflow_call:
    inputs:
      STATUS:
        required: true
        type: string
        description: "The status of the job (success, failure, or cancelled)"
      ENVIRONMENT:
          type: string
          description: 'Deployment Environment (e.g., dev, qa, prod)'
          required: false
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
        description: "The Slack Incoming Webhook URL"

jobs:
  notify:
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          # When using a webhook, we provide the URL and the payload
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
              {
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "Deployment of ${{github.repository}} ${{ inputs.STATUS == 'success' && 'succeeded ✅' ||  'failed ❌'}}",
                      "emoji": true
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Repo:* ${{ github.repository }}\n*Status:* ${{ inputs.STATUS }}\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Build Details>"
                    }
                  }
                ]
              }
